namespace Bartender.Net.Framework.User.PersonalStats;

// TODO Fix these caps
public interface IPersonalStats : IBartenderEntity {
    int Activestreak { get; }
    int Alcoholused { get; }
    int Argtravel { get; }
    int Arrestsmade { get; }
    int Attackcriticalhits { get; }
    int Attackdamage { get; }
    int Attackhits { get; }
    int Attackmisses { get; }
    int Attacksassisted { get; }
    int Attacksdraw { get; }
    int Attackslost { get; }
    int Attacksstealthed { get; }
    int Attackswon { get; }
    int Attackswonabroad { get; }
    int Auctionsells { get; }
    int Auctionswon { get; }
    int Awards { get; }
    int Axehits { get; }
    int Bazaarcustomers { get; }
    int Bazaarprofit { get; }
    int Bazaarsales { get; }
    int Bestactivestreak { get; }
    int Bestdamage { get; }
    int Bestkillstreak { get; }
    int Bloodwithdrawn { get; }
    int Booksread { get; }
    int Boostersused { get; }
    int Bountiescollected { get; }
    int Bountiesplaced { get; }
    int Bountiesreceived { get; }
    int Candyused { get; }
    int Cantaken { get; }
    int Cantravel { get; }
    int Caytravel { get; }
    int Chahits { get; }
    int Chitravel { get; }
    int Cityfinds { get; }
    int Cityitemsbought { get; }
    int Classifiedadsplaced { get; }
    int Companymailssent { get; }
    int Consumablesused { get; }
    int Contractscompleted { get; }
    int Counterfeiting { get; }
    int Criminaloffenses { get; }
    int Cybercrime { get; }
    int Daysbeendonator { get; }
    int Defendslost { get; }
    int Defendslostabroad { get; }
    int Defendsstalemated { get; }
    int Defendswon { get; }
    int Defense { get; }
    int Dexterity { get; }
    int Drugsused { get; }
    int Dubtravel { get; }
    int Dukecontractscompleted { get; }
    int Dumpfinds { get; }
    int Dumpsearches { get; }
    int Eastereggs { get; }
    int Eastereggsused { get; }
    int Elo { get; }
    int Endurance { get; }
    int Energydrinkused { get; }
    int Extortion { get; }
    int Exttaken { get; }
    int Factionmailssent { get; }
    int Failedbusts { get; }
    int Fraud { get; }
    int Friendmailssent { get; }
    int Grehits { get; }
    int H2hhits { get; }
    int Hawtravel { get; }
    int Heahits { get; }
    int Highestbeaten { get; }
    int Hollowammoused { get; }
    int Hospital { get; }
    int Illegalproduction { get; }
    int Illicitservices { get; }
    int Incendiaryammoused { get; }
    int Intelligence { get; }
    int Investedprofit { get; }
    int Itemsbought { get; }
    int Itemsboughtabroad { get; }
    int Itemsdumped { get; }
    int Itemslooted { get; }
    int Itemssent { get; }
    int Jailed { get; }
    int Japtravel { get; }
    int Jobpointsused { get; }
    int Kettaken { get; }
    int Killstreak { get; }
    int Largestmug { get; }
    int Lontravel { get; }
    int Lsdtaken { get; }
    int Machits { get; }
    int Mailssent { get; }
    int Manuallabor { get; }
    int Medicalitemsused { get; }
    int Meritsbought { get; }
    int Mextravel { get; }
    int Missioncreditsearned { get; }
    int Missionscompleted { get; }
    long Moneyinvested { get; }
    int Moneymugged { get; }
    int Nerverefills { get; }
    int Networth { get; }
    int Networthauctionhouse { get; }
    int Networthbank { get; }
    int Networthbazaar { get; }
    int Networthbookie { get; }
    int Networthcayman { get; }
    int Networthcompany { get; }
    int Networthdisplaycase { get; }
    int Networthenlistedcars { get; }
    int Networthitemmarket { get; }
    int Networthitems { get; }
    int Networthloan { get; }
    int Networthpending { get; }
    int Networthpiggybank { get; }
    int Networthpoints { get; }
    int Networthproperties { get; }
    int Networthstockmarket { get; }
    int Networthunpaidfees { get; }
    int Networthvault { get; }
    int Networthwallet { get; }
    int Onehitkills { get; }
    int Opitaken { get; }
    int Organisedcrimes { get; }
    int Overdosed { get; }
    int Pcptaken { get; }
    int Peoplebought { get; }
    int Peopleboughtspent { get; }
    int Peoplebusted { get; }
    int Personalsplaced { get; }
    int Piehits { get; }
    int Piercingammoused { get; }
    int Pishits { get; }
    int Pointsbought { get; }
    int Pointssold { get; }
    int Racesentered { get; }
    int Raceswon { get; }
    int Racingpointsearned { get; }
    int Racingskill { get; }
    int Raidhits { get; }
    int Rankedwarhits { get; }
    int Rankedwarringwins { get; }
    int Receivedbountyvalue { get; }
    int Refills { get; }
    int Rehabcost { get; }
    int Rehabs { get; }
    int Respectforfaction { get; }
    int Retals { get; }
    int Revives { get; }
    int Reviveskill { get; }
    int Revivesreceived { get; }
    int Rifhits { get; }
    int Roundsfired { get; }
    int Shohits { get; }
    int Shrtaken { get; }
    int Slahits { get; }
    int Smghits { get; }
    int Soutravel { get; }
    int Specialammoused { get; }
    int Speed { get; }
    int Spetaken { get; }
    int Spousemailssent { get; }
    int Statenhancersused { get; }
    int Stockfees { get; }
    int Stocklosses { get; }
    int Stocknetprofits { get; }
    int Stockpayouts { get; }
    int Stockprofits { get; }
    int Strength { get; }
    int Switravel { get; }
    int Territoryclears { get; }
    int Territoryjoins { get; }
    int Territorytime { get; }
    int Theft { get; }
    int Theyrunaway { get; }
    int Tokenrefills { get; }
    int Totalbountyreward { get; }
    int Totalbountyspent { get; }
    int Totalstats { get; }
    int Totalworkingstats { get; }
    int Tracerammoused { get; }
    int Trades { get; }
    int Trainsreceived { get; }
    int Traveltime { get; }
    int Traveltimes { get; }
    int Unarmoredwon { get; }
    int Useractivity { get; }
    int Vandalism { get; }
    int Victaken { get; }
    int Virusescoded { get; }
    int Weaponsbought { get; }
    int Xantaken { get; }
    int Yourunaway { get; }
}