namespace Bartender.Net.Framework.User.PersonalStats;

// TODO Fix these caps
public interface IPersonalStats : IBartenderEntity {
    int Activestreak { get; set; }
    int Alcoholused { get; set; }
    int Argtravel { get; set; }
    int Arrestsmade { get; set; }
    int Attackcriticalhits { get; set; }
    int Attackdamage { get; set; }
    int Attackhits { get; set; }
    int Attackmisses { get; set; }
    int Attacksassisted { get; set; }
    int Attacksdraw { get; set; }
    int Attackslost { get; set; }
    int Attacksstealthed { get; set; }
    int Attackswon { get; set; }
    int Attackswonabroad { get; set; }
    int Auctionsells { get; set; }
    int Auctionswon { get; set; }
    int Awards { get; set; }
    int Axehits { get; set; }
    int Bazaarcustomers { get; set; }
    int Bazaarprofit { get; set; }
    int Bazaarsales { get; set; }
    int Bestactivestreak { get; set; }
    int Bestdamage { get; set; }
    int Bestkillstreak { get; set; }
    int Bloodwithdrawn { get; set; }
    int Booksread { get; set; }
    int Boostersused { get; set; }
    int Bountiescollected { get; set; }
    int Bountiesplaced { get; set; }
    int Bountiesreceived { get; set; }
    int Candyused { get; set; }
    int Cantaken { get; set; }
    int Cantravel { get; set; }
    int Caytravel { get; set; }
    int Chahits { get; set; }
    int Chitravel { get; set; }
    int Cityfinds { get; set; }
    int Cityitemsbought { get; set; }
    int Classifiedadsplaced { get; set; }
    int Companymailssent { get; set; }
    int Consumablesused { get; set; }
    int Contractscompleted { get; set; }
    int Counterfeiting { get; set; }
    int Criminaloffenses { get; set; }
    int Cybercrime { get; set; }
    int Daysbeendonator { get; set; }
    int Defendslost { get; set; }
    int Defendslostabroad { get; set; }
    int Defendsstalemated { get; set; }
    int Defendswon { get; set; }
    int Defense { get; set; }
    int Dexterity { get; set; }
    int Drugsused { get; set; }
    int Dubtravel { get; set; }
    int Dukecontractscompleted { get; set; }
    int Dumpfinds { get; set; }
    int Dumpsearches { get; set; }
    int Eastereggs { get; set; }
    int Eastereggsused { get; set; }
    int Elo { get; set; }
    int Endurance { get; set; }
    int Energydrinkused { get; set; }
    int Extortion { get; set; }
    int Exttaken { get; set; }
    int Factionmailssent { get; set; }
    int Failedbusts { get; set; }
    int Fraud { get; set; }
    int Friendmailssent { get; set; }
    int Grehits { get; set; }
    int H2hhits { get; set; }
    int Hawtravel { get; set; }
    int Heahits { get; set; }
    int Highestbeaten { get; set; }
    int Hollowammoused { get; set; }
    int Hospital { get; set; }
    int Illegalproduction { get; set; }
    int Illicitservices { get; set; }
    int Incendiaryammoused { get; set; }
    int Intelligence { get; set; }
    int Investedprofit { get; set; }
    int Itemsbought { get; set; }
    int Itemsboughtabroad { get; set; }
    int Itemsdumped { get; set; }
    int Itemslooted { get; set; }
    int Itemssent { get; set; }
    int Jailed { get; set; }
    int Japtravel { get; set; }
    int Jobpointsused { get; set; }
    int Kettaken { get; set; }
    int Killstreak { get; set; }
    int Largestmug { get; set; }
    int Lontravel { get; set; }
    int Lsdtaken { get; set; }
    int Machits { get; set; }
    int Mailssent { get; set; }
    int Manuallabor { get; set; }
    int Medicalitemsused { get; set; }
    int Meritsbought { get; set; }
    int Mextravel { get; set; }
    int Missioncreditsearned { get; set; }
    int Missionscompleted { get; set; }
    long Moneyinvested { get; set; }
    int Moneymugged { get; set; }
    int Nerverefills { get; set; }
    int Networth { get; set; }
    int Networthauctionhouse { get; set; }
    int Networthbank { get; set; }
    int Networthbazaar { get; set; }
    int Networthbookie { get; set; }
    int Networthcayman { get; set; }
    int Networthcompany { get; set; }
    int Networthdisplaycase { get; set; }
    int Networthenlistedcars { get; set; }
    int Networthitemmarket { get; set; }
    int Networthitems { get; set; }
    int Networthloan { get; set; }
    int Networthpending { get; set; }
    int Networthpiggybank { get; set; }
    int Networthpoints { get; set; }
    int Networthproperties { get; set; }
    int Networthstockmarket { get; set; }
    int Networthunpaidfees { get; set; }
    int Networthvault { get; set; }
    int Networthwallet { get; set; }
    int Onehitkills { get; set; }
    int Opitaken { get; set; }
    int Organisedcrimes { get; set; }
    int Overdosed { get; set; }
    int Pcptaken { get; set; }
    int Peoplebought { get; set; }
    int Peopleboughtspent { get; set; }
    int Peoplebusted { get; set; }
    int Personalsplaced { get; set; }
    int Piehits { get; set; }
    int Piercingammoused { get; set; }
    int Pishits { get; set; }
    int Pointsbought { get; set; }
    int Pointssold { get; set; }
    int Racesentered { get; set; }
    int Raceswon { get; set; }
    int Racingpointsearned { get; set; }
    int Racingskill { get; set; }
    int Raidhits { get; set; }
    int Rankedwarhits { get; set; }
    int Rankedwarringwins { get; set; }
    int Receivedbountyvalue { get; set; }
    int Refills { get; set; }
    int Rehabcost { get; set; }
    int Rehabs { get; set; }
    int Respectforfaction { get; set; }
    int Retals { get; set; }
    int Revives { get; set; }
    int Reviveskill { get; set; }
    int Revivesreceived { get; set; }
    int Rifhits { get; set; }
    int Roundsfired { get; set; }
    int Shohits { get; set; }
    int Shrtaken { get; set; }
    int Slahits { get; set; }
    int Smghits { get; set; }
    int Soutravel { get; set; }
    int Specialammoused { get; set; }
    int Speed { get; set; }
    int Spetaken { get; set; }
    int Spousemailssent { get; set; }
    int Statenhancersused { get; set; }
    int Stockfees { get; set; }
    int Stocklosses { get; set; }
    int Stocknetprofits { get; set; }
    int Stockpayouts { get; set; }
    int Stockprofits { get; set; }
    int Strength { get; set; }
    int Switravel { get; set; }
    int Territoryclears { get; set; }
    int Territoryjoins { get; set; }
    int Territorytime { get; set; }
    int Theft { get; set; }
    int Theyrunaway { get; set; }
    int Tokenrefills { get; set; }
    int Totalbountyreward { get; set; }
    int Totalbountyspent { get; set; }
    int Totalstats { get; set; }
    int Totalworkingstats { get; set; }
    int Tracerammoused { get; set; }
    int Trades { get; set; }
    int Trainsreceived { get; set; }
    int Traveltime { get; set; }
    int Traveltimes { get; set; }
    int Unarmoredwon { get; set; }
    int Useractivity { get; set; }
    int Vandalism { get; set; }
    int Victaken { get; set; }
    int Virusescoded { get; set; }
    int Weaponsbought { get; set; }
    int Xantaken { get; set; }
    int Yourunaway { get; set; }
}