using Bartender.Net.Faction.Applications;
using Bartender.Net.Faction.Armor;
using Bartender.Net.Faction.ArmoryNews;
using Bartender.Net.Faction.AttackNews;
using Bartender.Net.Faction.Attacks;
using Bartender.Net.Faction.AttacksFull;
using Bartender.Net.Faction.Basic;
using Bartender.Net.Faction.Boosters;
using Bartender.Net.Faction.Caches;
using Bartender.Net.Faction.Chain;
using Bartender.Net.Faction.ChainReport;
using Bartender.Net.Faction.Chains;
using Bartender.Net.Faction.Common.Armory;
using Bartender.Net.Faction.Contributors;
using Bartender.Net.Faction.CrimeExp;
using Bartender.Net.Faction.CrimeNews;
using Bartender.Net.Faction.Crimes;
using Bartender.Net.Faction.Currency;
using Bartender.Net.Faction.Donations;
using Bartender.Net.Faction.Drugs;
using Bartender.Net.Faction.FundsNews;
using Bartender.Net.Faction.MainNews;
using Bartender.Net.Faction.Medical;
using Bartender.Net.Faction.MembershipNews;
using Bartender.Net.Faction.Positions;
using Bartender.Net.Faction.RankedWars;
using Bartender.Net.Faction.Reports;
using Bartender.Net.Faction.Revives;
using Bartender.Net.Faction.RevivesFull;
using Bartender.Net.Faction.Stats;
using Bartender.Net.Faction.Temporary;
using Bartender.Net.Faction.Territory;
using Bartender.Net.Faction.TerritoryNews;
using Bartender.Net.Faction.Upgrades;
using Bartender.Net.Faction.Weapons;
using Bartender.Net.Framework.Common.News;
using Bartender.Net.Framework.Common.Reports;
using Bartender.Net.Framework.Common.Revives;
using Bartender.Net.Framework.Common.RevivesFull;
using Bartender.Net.Framework.Key;
using Bartender.Net.Framework.Sections;

namespace Bartender.Net.Faction;

public class FactionSection {
    public static readonly Selection Applications = new ("applications", AccessLevel.Limited, typeof (FactionApplicationsRoot), typeof (FactionApplication));
    public static readonly Selection Armor = new ("armor", AccessLevel.Minimal, typeof (ArmorRoot), typeof (FactionLoanable));
    public static readonly Selection ArmoryNews = new ("armorynews", AccessLevel.Minimal, typeof (ArmoryNewsRoot), typeof (NewsEntry));
    public static readonly Selection AttackNews = new ("attacknews", AccessLevel.Limited, typeof (AttackNewsRoot), typeof (NewsEntry));
    public static readonly Selection Attacks = new ("attacks", AccessLevel.Limited, typeof (FactionAttacksRoot), typeof (FactionAttack));
    public static readonly Selection AttacksFull = new ("attacksfull", AccessLevel.Limited, typeof (FactionAttacksFullRoot), typeof (FactionAttackFull));
    public static readonly Selection Basic = new ("basic", AccessLevel.Public, typeof (FactionBasic), typeof (FactionBasic));
    public static readonly Selection Boosters = new ("boosters", AccessLevel.Minimal, typeof (BoostersRoot), typeof (FactionArmoryItem));
    public static readonly Selection Caches = new ("caches", AccessLevel.Limited, typeof (CachesRoot), typeof (FactionArmoryItem));
    public static readonly Selection Chain = new ("chain", AccessLevel.Public, typeof (ChainRoot), typeof (CurrentChain));
    public static readonly Selection ChainReport = new ("chainreport", AccessLevel.Public, typeof (ChainReportRoot), typeof (FactionChainReport));
    public static readonly Selection Chains = new ("chains", AccessLevel.Minimal, typeof (ChainsRoot), typeof (FactionChain));
    public static readonly Selection Contributors = new ("contributors", AccessLevel.Limited, typeof (ContributorsRoot), typeof (StatContributors));
    public static readonly Selection CrimeExp = new ("crimeexp", AccessLevel.Minimal, typeof (CrimeExpRoot), typeof (CrimeExpRoot));
    public static readonly Selection CrimeNews = new ("crimenews", AccessLevel.Minimal, typeof (CrimeNewsRoot), typeof (NewsEntry));
    public static readonly Selection Crimes = new ("crimes", AccessLevel.Minimal, typeof (FactionCrimesRoot), typeof (FactionCrime));
    public static readonly Selection Currency = new ("currency", AccessLevel.Limited, typeof (CurrencyRoot), typeof (CurrencyRoot));
    public static readonly Selection Donations = new ("donations", AccessLevel.Limited, typeof (DonationsRoot), typeof (DonationEntry));
    public static readonly Selection Drugs = new ("drugs", AccessLevel.Minimal, typeof (DrugsRoot), typeof (FactionArmoryItem));
    public static readonly Selection FundsNews = new ("fundsnews", AccessLevel.Limited, typeof (FundsNewsRoot), typeof (NewsEntry));
    public static readonly Selection MainNews = new ("mainnews", AccessLevel.Minimal, typeof (MainNewsRoot), typeof (NewsEntry));
    public static readonly Selection Medical = new ("medical", AccessLevel.Minimal, typeof (MedicalRoot), typeof (FactionArmoryItem));
    public static readonly Selection MembershipNews = new ("membershipnews", AccessLevel.Minimal, typeof (MembershipNewsRoot), typeof (NewsEntry));
    public static readonly Selection Positions = new ("positions", AccessLevel.Minimal, typeof (PositionsRoot), typeof (Position));
    public static readonly Selection RankedWars = new ("rankedwars", AccessLevel.Public, typeof (RankedWarsRoot), typeof (RankedWarEntry));
    public static readonly Selection Reports = new ("reports", AccessLevel.Limited, typeof (FactionReportsRoot), typeof (Report));
    public static readonly Selection Revives = new ("revives", AccessLevel.Minimal, typeof (FactionRevivesRoot), typeof (Revive));
    public static readonly Selection RevivesFull = new ("revivesfull", AccessLevel.Minimal, typeof (FactionReviveFullRoot), typeof (ReviveFull));
    public static readonly Selection Stats = new ("stats", AccessLevel.Minimal, typeof (StatsRoot), typeof (StatsEntry));
    public static readonly Selection Temporary = new ("temporary", AccessLevel.Minimal, typeof (TemporaryRoot), typeof (FactionLoanable));
    public static readonly Selection Territory = new ("territory", AccessLevel.Public, typeof (TerritoryRoot), typeof (FactionTerritory));
    public static readonly Selection TerritoryNews = new ("territorynews", AccessLevel.Minimal, typeof (TerritoryNewsRoot), typeof (NewsEntry));
    public static readonly Selection Upgrades = new ("upgrades", AccessLevel.Minimal, typeof (UpgradesRoot), typeof (UpgradesRoot));
    public static readonly Selection Weapons = new ("weapons", AccessLevel.Minimal, typeof (WeaponsRoot), typeof (FactionLoanable));

    public static IEnumerable<Selection> Selections {
        get {
            yield return Applications;
            yield return Armor;
            yield return ArmoryNews;
            yield return AttackNews;
            yield return Attacks;
            yield return AttacksFull;
            yield return Basic;
            yield return Boosters;
            yield return Caches;
            yield return Chain;
            yield return ChainReport;
            yield return Chains;
            yield return Contributors;
            yield return CrimeExp;
            yield return CrimeNews;
            yield return Crimes;
            yield return Currency;
            yield return Donations;
            yield return Drugs;
            yield return FundsNews;
            yield return MainNews;
            yield return Medical;
            yield return MembershipNews;
            yield return Positions;
            yield return RankedWars;
            yield return Reports;
            yield return Revives;
            yield return RevivesFull;
            yield return Stats;
            yield return Temporary;
            yield return Territory;
            yield return TerritoryNews;
            yield return Upgrades;
            yield return Weapons;
        }
    }
}
